CREATE TABLE BOOKING (
  B_ID VARCHAR2(100),
  S_ID VARCHAR2(100),
  SEAT_IDS VARCHAR2(4000),
  B_AMOUNT NUMBER,
  B_STATUS VARCHAR2(200),
  B_DATE TIMESTAMP,
  T_ID VARCHAR2(100),
  PRIMARY KEY (B_ID),
  FOREIGN KEY (S_ID) REFERENCES SHOW(S_ID),
  FOREIGN KEY (T_ID) REFERENCES THEATER(T_ID)
);