CREATE TABLE CITY (
  C_ID VARCHAR2(100),
  C_NAME VARCHAR2(200),
  PRIMARY KEY (C_ID),
);


INSERT INTO CITY VALUES('C_1001', 'PUNE');
INSERT INTO CITY VALUES('C_1002', 'MUMBAI');
INSERT INTO CITY VALUES('C_1003', 'BENGALURU');
INSERT INTO CITY VALUES('C_1004', 'CHENNAI');
INSERT INTO CITY VALUES('C_1005', 'KOLKATA');
INSERT INTO CITY VALUES('C_1006', 'DELHI');